<?php
    session_start();
    $servername = "localhost";
    $username = "id1863335_root";
    $password = "abhishek";
    $dbname = "id1863335_arduino";
    $conn = mysqli_connect($servername, $username, $password, $dbname);
    if (!$conn) {
        die("Connection failed: " . mysqli_connect_error());
    }
    if($_SESSION['acctype']=== "Consumer"){
            $sql = "SELECT uname,pass FROM register ";
        } elseif($_SESSION['acctype']=== "Admin") {
            $sql = "SELECT uname,pass FROM admin";
        }
    $result = mysqli_query($conn, $sql);
    if (mysqli_num_rows($result) > 0) {
            while($row = mysqli_fetch_assoc($result)) {
                if( ($_SESSION['uname'] === $row['uname']) && $_SESSION['pass'] === $row['pass']) {
                    $error="none";
                    break;
                }     
            }
        }
    else {
        mysqli_close($conn);
        //echo 'index page<br> device not registered';
        header("Location:index.php");
    }
    mysqli_close($conn);
    if($error!="none"){
        //echo 'error present';
        header("Location:index.php");
    }
?>
<html>
<title>LT Energy Bill</title>
<link rel="stylesheet" href="css/text.css" type="text/css">
<link rel="stylesheet" href="css/menu.css" type="text/css">
<body>
<div id="Main">
	<div id="Header"> 
        <h1>Arduino Smart Metering<br>(LT I Res 1-Phase)</h1>
        </div>
	<div id="Menu">
		<ul>
                    <li ><a href="logout.php"><font id="Logout">LOGOUT<br><?php echo $_SESSION['uname']."(".$_SESSION['acctype'].")"; ?></font></a></li>
                    <li><a href="about.php">ABOUT</a></li>
                    <?php 
                        if($_SESSION['acctype']==="Consumer"){
                            echo '<li><a href="usage.php" >USAGE</a></li>';
                        }
                        else{
                            echo '<li><a href="manage.php" >MANAGE</a></li>';
                        }
                    ?>
                    <li class="active"><a href="home.php"><b id="active">HOME</b></a></li>
		</ul>
        </div>
	<div id="Info" align="center">
            <br><br>
            Every Management System, Billing System is trying to make the automatic, portable and<br>
            remote control. This paper presents a Smart Energy Metering System for automatic and flexible and<br>
            billing system. Using the Arduino with Ethernet Shield provide the meter reading system with designing <br>
            Interrupts as per our requirement so that we could get an accurate Reading. The proposed energy<br>
            metering system can implement with Open Source Hardware like Arduino and Ethernet Shield to transmit the data, <br>
            pulses generated by meter, security services, calculated bill over the Internet. In recent years, <br>
            a wide variety of solutions has been proposed for the data transmission and remote measurement. <br>
            In this Project, an architecture of a real-time smart energy management with billing feature is presented. <br>
            It provides several Smart Meters, that continuously monitor connected loads and communicate with Arduino. <br>
            The main task of Arduino is to catch the pulse of the Meter and then fire a query in the database to store <br>
            the pulse as well as calculate kWh forwarded from a single smart meter, in order to<br>
            make this information available on Internet using HTTP server.
	</div>
	<div id="Footer" align="center">
            &copy;Abhishek Katyare and Friends
	</div>
</div>
</body>
</html>